-- CREATE USER c##botadmin IDENTIFIED BY BotWelcome123$$;
-- GRANT CONNECT TO c##botadmin;
-- GRANT CONNECT, RESOURCE TO c##botadmin;
-- GRANT UNLIMITED TABLESPACE TO c##botadmin;

CREATE TABLE SSP_LOCAL_GLN_USER 
(
  ORG_CODE VARCHAR2(256) NOT NULL 
, LOCAL_GLN_UUID VARCHAR2(256) 
);

CREATE TABLE SSP_TRANSACTIONS 
(
  REQ_ORG_CODE VARCHAR2(50) 
, REQ_ORG_TX_DATE VARCHAR2(20) 
, REQ_ORG_TX_TIME VARCHAR2(20) 
, GLN_TX_NO VARCHAR2(50) 
, PAY_CODE VARCHAR2(50) 
, BAR_CODE VARCHAR2(256) 
, QR_CODE VARCHAR2(256) 
, VALID_SECOND INT 
, ORIG_BALANCE FLOAT 
, NEW_BALANCE FLOAT 
, TX_AMT FLOAT 
, TX_CUR VARCHAR2(20) 
, TX_EX_RATE FLOAT 
, STATUS VARCHAR2(20) 
, APPROVE_DATETIME VARCHAR2(20) 
);
